apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inbound-to-service-b-vs
spec:
  hosts:
    - "*"
  gateways:
    - service-b-gw
  http:
    - match:
        - uri:
            exact: /service-b
      rewrite:
        uri: /
      route:
        - destination:
            host: producer-internal-host
            port:
              number: 80