apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: external-cluster-dr
spec:
  host: istio-ingressgateway.istio-system.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE