apiVersion: v1
kind: Service
metadata:
  name: service-a-srv
  labels:
    app: service-a-app
    service: service-a-app-srv
spec:
  ports:
    - port: 80
      name: http-80
      targetPort: 8081
  selector:
    app: service-a-app