apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-ext-host-se
spec:
  hosts:
    - istio-ingressgateway.istio-system.svc.cluster.local
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL